### ISSUE TITLE
Allow searching on types only through kibana

### ISSUE THREAD

**Issue by djtecha** [floragunncom/search-guard#134]
So, I'm trying to limit what type is available to anonymous users which appears to work on the backend (via curl) but fails to work through kibana 4.5. This leads to complaining about the following paths:   indices:data/read/field_stats* indices:data/read/msearch indices:data/read/search

Now if I add those with something like:
```
    '*':
      '*':
        - indices:data/read/field_stats*
        - indices:data/read/msearch
        - indices:data/read/search
```
for the public user it works but then the restriction by type no longer works.

Here are my current yml:

**sg_roles.yml**

```
sg_public:
  cluster:
      - cluster:monitor/nodes/info
      - cluster:monitor/health
  indices:
    '*':
      '*_public':
        - 'indices:*'
    '?kibana':
      '*':
        - indices:admin/refresh*
        - indices:admin/template/get
        - indices:admin/exists
        - indices:data/write/bulk
        - indices:admin/mappings/fields/get*
        - indices:admin/refresh
        - indices:admin/validate/query
        - indices:data/read/get
        - indices:data/read/mget*
        - indices:data/read/search
        - indices:data/read/msearch
```
**sg_roles_mapping.yml**
``` 
sg_public:
  users:
    - '*'
