### ISSUE TITLE
indices:admin/create requires a wildcard

### ISSUE THREAD

**Issue by Adirelle** [floragunncom/search-guard#155]
It seems a wildcard is required for the `indices:admin:create` permission to work.

With this :

```yml
sg_myindex_admin:
  indices:
    'myindex*':
      '*':
        - ALL
```

Everything is fine. The users with `sg_myindex_admin` role can create and/or delete `myindex`.

But with :

```yml
sg_myindex_admin:
  indices:
    myindex:
      '*':
        - ALL
```

I get an error: `no permissions for indices:admin/create`.
