### ISSUE TITLE
no permissions for indices:data/write/bulk[s]

### ISSUE THREAD

**Issue by linhntt41** [floragunncom/search-guard#160]
I using logstash with search-guard, index kt-2016.07.05 stored in ES
 but why logs logstash  "error"=>{"type"=>"security_exception", "reason"=>"no permissions for indices:data/write/bulk[s]"}}}, :level=>:warn}`
version: logstash 2.3.3, es: 2.3.3, search-guard: 2.3.3, kibana:4.5,
This file config:
sg_roles.yml
```
sg_logstash:
  cluster:
    - indices:admin/template/get
    - indices:admin/template/put
  indices:
    'kt-*':
      '*':
        - indices:data/write/bulk
        - indices:data/write/delete
        - indices:data/write/update
        - indices:data/read/search
        - indices:data/read/scroll
        - CREATE_INDEX
```
sg_roles_mapping.yml
```
sg_logstash:
  users:
    - logstash
```
sg_internal_users.yml
```
logstash:
  hash: $2a$12$u1ShR4l4uBS3Uv59Pa2y5.1uQuZBrZtmNfqB3iM/.jL0XoV9sghS2
  #password is: logstash
```
bin/logstash -f test.conf 
Settings: Default pipeline workers: 1
Pipeline main started
{
       "message" => "2016-07-05 16:47:50 linh in",
      "@version" => "1",
    "@timestamp" => "2016-07-05T09:47:27.338Z",
          "path" => "/opt/poc.log",
          "host" => "osboxes",
     "timestamp" => "2016-07-05 16:47:50",
      "username" => "linh",
        "status" => "in"
}
`Failed action.  {:status=>403, :action=>["index", {:_id=>nil, :_index=>"kt-2016.07.05", :_type=>"logs", :_routing=>nil}, #<LogStash::Event:0xb0d827 @metadata_accessors=#<LogStash::Util::Accessors:0x192a8b5 @store={"path"=>"/opt/poc.log"}, @lut={"[path]"=>[{"path"=>"/opt/poc.log"}, "path"]}>, @cancelled=false, @data={"message"=>"2016-07-05 16:47:50 linh in", "@version"=>"1", "@timestamp"=>"2016-07-05T09:47:27.338Z", "path"=>"/opt/poc.log", "host"=>"osboxes", "timestamp"=>"2016-07-05 16:47:50", "username"=>"linh", "status"=>"in"}, @metadata={"path"=>"/opt/poc.log"}, @accessors=#<LogStash::Util::Accessors:0x1650475 @store={"message"=>"2016-07-05 16:47:50 linh in", "@version"=>"1", "@timestamp"=>"2016-07-05T09:47:27.338Z", "path"=>"/opt/poc.log", "host"=>"osboxes", "timestamp"=>"2016-07-05 16:47:50", "username"=>"linh", "status"=>"in"}, @lut={"path"=>[{"message"=>"2016-07-05 16:47:50 linh in", "@version"=>"1", "@timestamp"=>"2016-07-05T09:47:27.338Z", "path"=>"/opt/poc.log", "host"=>"osboxes", "timestamp"=>"2016-07-05 16:47:50", "username"=>"linh", "status"=>"in"}, "path"], "host"=>[{"message"=>"2016-07-05 16:47:50 linh in", "@version"=>"1", "@timestamp"=>"2016-07-05T09:47:27.338Z", "path"=>"/opt/poc.log", "host"=>"osboxes", "timestamp"=>"2016-07-05 16:47:50", "username"=>"linh", "status"=>"in"}, "host"], "message"=>[{"message"=>"2016-07-05 16:47:50 linh in", "@version"=>"1", "@timestamp"=>"2016-07-05T09:47:27.338Z", "path"=>"/opt/poc.log", "host"=>"osboxes", "timestamp"=>"2016-07-05 16:47:50", "username"=>"linh", "status"=>"in"}, "message"], "timestamp"=>[{"message"=>"2016-07-05 16:47:50 linh in", "@version"=>"1", "@timestamp"=>"2016-07-05T09:47:27.338Z", "path"=>"/opt/poc.log", "host"=>"osboxes", "timestamp"=>"2016-07-05 16:47:50", "username"=>"linh", "status"=>"in"}, "timestamp"], "username"=>[{"message"=>"2016-07-05 16:47:50 linh in", "@version"=>"1", "@timestamp"=>"2016-07-05T09:47:27.338Z", "path"=>"/opt/poc.log", "host"=>"osboxes", "timestamp"=>"2016-07-05 16:47:50", "username"=>"linh", "status"=>"in"}, "username"], "status"=>[{"message"=>"2016-07-05 16:47:50 linh in", "@version"=>"1", "@timestamp"=>"2016-07-05T09:47:27.338Z", "path"=>"/opt/poc.log", "host"=>"osboxes", "timestamp"=>"2016-07-05 16:47:50", "username"=>"linh", "status"=>"in"}, "status"], "type"=>[{"message"=>"2016-07-05 16:47:50 linh in", "@version"=>"1", "@timestamp"=>"2016-07-05T09:47:27.338Z", "path"=>"/opt/poc.log", "host"=>"osboxes", "timestamp"=>"2016-07-05 16:47:50", "username"=>"linh", "status"=>"in"}, "type"]}>>], :response=>{"create"=>{"_index"=>"kt-2016.07.05", "_type"=>"logs", "_id"=>"AVW6dIzLO4Sg210-8PKF", "status"=>403, "error"=>{"type"=>"security_exception", "reason"=>"no permissions for indices:data/write/bulk[s]"}}}, :level=>:warn}`

**Comment by floragunncom** [comment]
try

```
sg_logstash:
  cluster:
    - indices:admin/template/get
    - indices:admin/template/put
  indices:
    'kt-*':
      '*':
        - CRUD
        - CREATE_INDEX
```

as shown here: https://github.com/floragunncom/search-guard/blob/master/sgconfig/sg_roles.yml
