### ISSUE TITLE
Can't delete templates

### ISSUE THREAD

**Issue by djtecha** [floragunncom/search-guard#163]
Trying to delete a template via:
**curl -XDELETE localhost:9200/_template/test?pretty -uadmin:passwd**

And I get:

```
{
  "error" : {
    "root_cause" : [ {
      "type" : "security_exception",
      "reason" : "no permissions for indices:admin/template/delete"
    } ],
    "type" : "security_exception",
    "reason" : "no permissions for indices:admin/template/delete"
  },
  "status" : 403
}
```

I can do pretty much anything else with that user, like add that template in the first place. Here is my sg_roles.yml

```
sg_admin:
  cluster:
    - '*'
  indices:
    '*':
      '*':
        - '*'
```
