### ISSUE TITLE
Searchguard doens't fail over with Multiple authc defined

### ISSUE THREAD

**Issue by ewolinetz** [floragunncom/search-guard#166]
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)

sh-4.2$ cat /etc/system-release
CentOS Linux release 7.2.1511 (Core)

ES Version 2.3.3-1
SG Versions:
com.floragunn/search-guard-ssl/2.3.3.13
com.floragunn/search-guard-2/2.3.3.2

sg_config.yaml:
```
searchguard:
  dynamic:
    http:
      xff:
        enabled: true
        remoteIpHeader: "x-forwarded-for"
        proxiesHeader: "x-forwarded-by"
        trustedProxies: ".*"
        internalProxies: ".*"
    authc:
      authentication_domain_proxy:
        enabled: true
        order: 0
        authentication_backend:
          type: com.floragunn.searchguard.auth.internal.NoOpAuthenticationBackend
        authorization_backend:
          type: com.floragunn.searchguard.auth.internal.NoOpAuthorizationBackend
        http_authenticator:
          type: com.floragunn.searchguard.http.HTTPProxyAuthenticator
          challenge: false
          config:
            user_header: "X-Proxy-Remote-User"
            roles_header: "x-proxy-roles"
      authentication_domain_basic_internal:
        enabled: true
        order: 0
        authentication_backend:
          type: com.floragunn.searchguard.auth.internal.NoOpAuthenticationBackend
        authorization_backend:
          type: com.floragunn.searchguard.auth.internal.NoOpAuthorizationBackend
        http_authenticator:
          type: com.floragunn.searchguard.http.HTTPClientCertAuthenticator
          challenge: false
```

When my Kibana tries to connect upon it starting up, it doesn't have a proxy header and _should_ connect via the HTTPClientCertAuthenticator however Searchguard never tries to pull the client cert.
I have observed that when xff is `enabled: false` this works.

I see this repeat in my Elasticsearch logs with TRACE for com.floragunn.searchguard.http:
```
[2016-07-08 20:41:46,601][TRACE][com.floragunn.searchguard.http.SearchGuardHttpServerTransport] [Baron Blood] channel opened: [id: 0x6d83a30b, /172.17.0.3:59744 => /172.17.0.4:9200]
[2016-07-08 20:41:46,647][DEBUG][com.floragunn.searchguard.http.XFFResolver] xff resolve /172.17.0.3:59744
[2016-07-08 20:41:46,647][TRACE][com.floragunn.searchguard.http.RemoteIpDetector] originalRemoteAddr 172.17.0.3
[2016-07-08 20:41:46,647][ERROR][com.floragunn.searchguard.http.RemoteIpDetector] no remote ip
[2016-07-08 20:41:46,656][TRACE][com.floragunn.searchguard.http.SearchGuardHttpServerTransport] [Baron Blood] channel closed: [id: 0x6d83a30b, /172.17.0.3:59744 => /172.17.0.4:9200]
```

I have also noticed that `com.floragunn.searchguard.http.RemoteIpDetector` does not read in from configuration to populate `proxiesHeader` and `remoteIpHeader`.
