### ISSUE TITLE
Using aliases allow access to all index data

### ISSUE THREAD

**Issue by kiblik** [floragunncom/search-guard#190]
I defined more aliases on one index using different filters.
```
- alias1: {"term":{"_type":"category1"}}
- alias2: {"term":{"_type":"category2"}}
```
I allowed access for users:
```
sg_user1:
  indices:
    'alias1':
      '*':
        - READ
sg_user2:
  indices:
    'alias2':
      '*':
        - READ
```

I hope that sg_user1 will read data with filter `{"term":{"_type":"category1"}}` but sg_user1 has got also access to other data in index.

ES: 2.3.4
SG: 2.3.4.3
OS: Ubuntu 14.04.4 LTS
Java: OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)
Cluster: one client-node and one data-node
