### ISSUE TITLE
Proxy - documentation, default values and implementation inconsistention

### ISSUE THREAD

**Issue by kiblik** [floragunncom/search-guard#255]
[Documentation](https://github.com/floragunncom/search-guard-docs/blob/master/proxy.md) and [default values](https://github.com/floragunncom/search-guard/blob/5.1.1/sgconfig/sg_config.yml#L55-L59) use this structure of configuration:
```
searchguard:
  dynamic:
    http:
      xff:
        internalProxies: '192\.168\.0\.10|192\.168\.0\.11' # regex pattern
        remoteIpHeader:  'x-forwarded-for'
        proxiesHeader:   'x-forwarded-by'
        trustedProxies: '.*' # trust all external proxies, regex pattern
```
But [XFFResolver](https://github.com/floragunncom/search-guard/blob/master/src/main/java/com/floragunn/searchguard/http/XFFResolver.java#L90-L93) needs different structure of configuration. Like:
```
searchguard:
  dynamic:
    http:
      xff:
        internalProxies: '192\.168\.0\.10|192\.168\.0\.11' # regex pattern
        proxiesHeader:
          remoteIpHeader:  'x-forwarded-for'
          trustedProxies: '.*' # trust all external proxies, regex pattern
```
This parsing use may corrupt on `proxiesHeader`.
