### ISSUE TITLE
Upgrading ES+SG to 5.0.1-8 fails to upload new SG index

### ISSUE THREAD

**Issue by bw498c** [floragunncom/search-guard#260]
We are having an issue upgrading a 3 node cluster from ES 2.3.1 with search-guard-2-2.3.1.0-beta1 to ES 5.0.1 with SG 5.0.1-8. The old SG index is unusable by the new SG, but we are unsuccessful in uploading a new searchguard index using `sgadmin`.

Our upgrage process is a full cluster restart upgrade, following the [ES docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/restart-upgrade.html), upgrading to the new search guard in step 4. After the upgrade, SG is not "initialized" so we attempt to upload a new SG index using `sgadmin`.  Here is the attempt:

```console
$ ./plugins/search-guard-5/tools/sgadmin.sh -cd config/ -ks config/admin-keystore.jks -ts config/truststore.jks -nhnv -kspass password -tspass password -cn my-cluster
Search Guard Admin v5
Will connect to localhost:9300 ... done
Contacting elasticsearch cluster 'my-cluster' and wait for YELLOW clusterstate ...
Cannot retrieve cluster state due to None of the configured nodes are available: [{#transport#-1}{wbF7QKcMSJuxHfrkC03Law}{127.0.0.1}{127.0.0.1:9300}]. This is not an error, will keep on trying ...
Cannot retrieve cluster state due to None of the configured nodes are available: [{#transport#-1}{wbF7QKcMSJuxHfrkC03Law}{127.0.0.1}{127.0.0.1:9300}]. This is not an error, will keep on trying ...
Cannot retrieve cluster state due to None of the configured nodes are available: [{#transport#-1}{wbF7QKcMSJuxHfrkC03Law}{127.0.0.1}{127.0.0.1:9300}]. This is not an error, will keep on trying ...
Cannot retrieve cluster state due to None of the configured nodes are available: [{#transport#-1}{wbF7QKcMSJuxHfrkC03Law}{127.0.0.1}{127.0.0.1:9300}]. This is not an error, will keep on trying ...
Cannot retrieve cluster state due to None of the configured nodes are available: [{#transport#-1}{wbF7QKcMSJuxHfrkC03Law}{127.0.0.1}{127.0.0.1:9300}]. This is not an error, will keep on trying ...
Cannot retrieve cluster state due to None of the configured nodes are available: [{#transport#-1}{wbF7QKcMSJuxHfrkC03Law}{127.0.0.1}{127.0.0.1:9300}]. This is not an error, will keep on trying ...
Cannot retrieve cluster state due to None of the configured nodes are available: [{#transport#-1}{wbF7QKcMSJuxHfrkC03Law}{127.0.0.1}{127.0.0.1:9300}]. This is not an error, will keep on trying ...
Cannot retrieve cluster state due to None of the configured nodes are available: [{#transport#-1}{wbF7QKcMSJuxHfrkC03Law}{127.0.0.1}{127.0.0.1:9300}]. This is not an error, will keep on trying ...
Cannot retrieve cluster state due to None of the configured nodes are available: [{#transport#-1}{wbF7QKcMSJuxHfrkC03Law}{127.0.0.1}{127.0.0.1:9300}]. This is not an error, will keep on trying ...
[repeated till it times out]
```

The debugged logs of the ES node display the following during this running of `sgadmin`:
```
[2016-12-20T11:39:17,974][DEBUG][i.n.h.s.SslHandler       ] [id: 0xb1f55180, L:/127.0.0.1:9300 - R:/127.0.0.1:58266] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
[2016-12-20T11:39:17,977][ERROR][c.f.s.t.SearchGuardRequestHandler] Cannot authenticate null
[2016-12-20T11:39:23,078][DEBUG][i.n.h.s.SslHandler       ] [id: 0xb07519c9, L:/127.0.0.1:9300 - R:/127.0.0.1:58270] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
[2016-12-20T11:39:23,083][ERROR][c.f.s.t.SearchGuardRequestHandler] Cannot authenticate null
[repeated many times]
```

Search Guard was in an uninitialized state before and after the attempt with `sgadmin` :
```console
$ curl -k https://localhost:9200
Search Guard not initialized (SG11)
```

What we have tried:
* Tried using `-icl` instead of `-cn` (according to [this issue](https://github.com/floragunncom/search-guard/issues/246)): no effect
* Tried specifying `-h` to specify host, trying all hosts: same results for all hosts
* Removing the SG plugin, and check cluster state: Green
  ```console
  $ curl http://localhost:9200/_cluster/health
  {"cluster_name":"geolink-upgrade-cert","status":"green","timed_out":false,"number_of_nodes":3,"number_of_data_nodes":3,"active_primary_shards":6,"active_shards":12,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":0,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":100.0}
  ```
* Delete old SG index, then add the SG plugin back: no effect on `sgadmin`
* Disable SG and just use SG-SSL (just to rule out ssl): Cluster is still Green, same as above

ES YAML:
``` yaml
cluster.name: my-cluster
node.name: my-node1.my-cluster.com
node.master: true  
node.data: true
node.max_local_storage_nodes: 1
path.conf: /opt/app/elasticsearch/config
path.data: /opt/app/elasticsearch/data
path.logs: /opt/app/elasticsearch/logs
bootstrap.memory_lock: true
network.bind_host: 0.0.0.0
network.publish_host: xxx.xxx.xxx.xxx
transport.tcp.port: 9300
transport.tcp.compress: false
http.port: 9200
http.max_content_length: 100mb
http.enabled: true
http.cors.enabled: false
http.cors.allow-origin: /http:\/\/my-node1\.my-cluster\.com:18890/
http.cors.allow-headers: X-Requested-With, Content-Type, Content-Length
http.cors.allow-credentials: false
gateway.recover_after_nodes: 1
gateway.recover_after_time: 5m
gateway.expected_nodes: 2
indices.recovery.max_bytes_per_sec: 20mb
discovery.zen.minimum_master_nodes: 2
discovery.zen.ping_timeout: 3s
discovery.zen.ping.unicast.hosts: ["my-node1.my-cluster.com","my-node2.my-cluster.com","my-node3.my-cluster.com"]
searchguard.ssl.transport.enable_openssl_if_available: true
searchguard.ssl.transport.enabled: true
searchguard.ssl.transport.keystore_type: JKS
searchguard.ssl.transport.keystore_filepath: my-node1.my-cluster.com-keystore.jks
searchguard.ssl.transport.keystore_password: password
searchguard.ssl.transport.truststore_type: JKS
searchguard.ssl.transport.truststore_filepath: truststore.jks
searchguard.ssl.transport.truststore_password: password
searchguard.ssl.http.enable_openssl_if_available: true
searchguard.ssl.http.enabled: true
searchguard.ssl.http.keystore_type: JKS
searchguard.ssl.http.keystore_filepath: my-node1.my-cluster.com-keystore.jks
searchguard.ssl.http.keystore_password: password
searchguard.ssl.http.truststore_type: JKS
searchguard.ssl.http.truststore_filepath: truststore.jks
searchguard.ssl.http.truststore_password: password
searchguard.authcz.admin_dn:
 - cn=admin,ou=my-unit,o=my-org,L=Atlanta,C=US
```

Other info:
```console
$ java -version
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
$ cat /etc/system-release
Red Hat Enterprise Linux Server release 6.8 (Santiago)
```
