### ISSUE TITLE
LDAP authz not working with role DN, only role CN

### ISSUE THREAD

**Issue by matejzero** [floragunncom/search-guard#261]
Hello,

I'm trying to setup LDAP authz and I'm having some problems. It is working, but not the way I want / should suppose to.

My system:
- ES 5.1.1
- SG 5.1.1-9 with LDAP module version 5.0-5
- OpenJDK 1.8.0.111 (CentOS 7)
- Single node server

I have my ldap auth set up like:
```yaml
    authz:
      roles_from_myldap:
        enabled: true
        authorization_backend:
          type: ldap
          config:
            # enable ldaps
            enable_ssl: false
            # enable start tls, enable_ssl should be false
            enable_start_tls: false
            # send client certificate
            enable_ssl_client_auth: false
            # verify ldap hostname
            verify_hostnames: true
            hosts:
              - ad.example.com:389
            bind_dn: 'CN=Elasticsearch Searchguard,OU=SAP,DC=ad,DC=example,DC=com'
            password: 'password'
            rolebase: 'OU=Groups,DC=ad,DC=example,DC=com'
            # Filter to search for roles (currently in the whole subtree beneath rolebase)
            # {0} is substituted with the DN of the user
            # {1} is substituted with the username
            # {2} is substituted with an attribute value from user's directory entry, of the   authenticated user. Use userroleattribute to specify the name of the attribute
            rolesearch: '(member={0})'
            # Specify the name of the attribute which value should be substituted with {2} above
            userroleattribute: null
            # Roles as an attribute of the user entry
            userrolename: memberOf
            # The attribute in a role entry containing the name of that role
            rolename: dn
            # Resolve nested roles transitive (roles which are members of other roles and so on ...)
            resolve_nested_roles: true
            userbase: 'OU=SAP,DC=ad,DC=example,DC=com'
            # Filter to search for users (currently in the whole subtree beneath userbase)
            # {0} is substituted with the username
            usersearch: '(sAMAccountName={0})'
```

My role:
```
dn: CN=Elasticsearch SAP,OU=Elasticsearch,OU=Groups,DC=ad,DC=example,DC=com
objectClass: top
objectClass: group
cn: Elasticsearch SAP
member: CN=Elasticsearch Sap2,OU=SAP,DC=ad,DC=example,DC=com
member: CN=Elasticsearch Sap1,OU=SAP,DC=ad,DC=example,DC=com
distinguishedName: CN=Elasticsearch SAP,OU=Elasticsearch,OU=Groups,DC=ad,DC=example,DC=com
name: Elasticsearch SAP
sAMAccountName: Elasticsearch SAP
```

Now, if I enter roles `cn` into sg_roles_mapping, my user is correctly mapped to the role, but if I enter `dn`, then it fails to get any role:
Working:
```
sg_role_sap:
  backendroles:
    - 'Elasticsearch SAP'
```

Not working:
```
sg_role_sap:
  backendroles:
    - 'CN=Elasticsearch SAP,OU=Elasticsearch,OU=Groups,DC=ad,DC=example,DC=com'
```

In the logs, I see something about NullPointException: `[c.f.d.a.l.b.LDAPAuthorizationBackend] Unable to fill user roles due to java.lang.NullPointerException`.

I read docs multiple times and I think this is not a configuration error, but I could be wrong.
It looks like [this user](https://groups.google.com/forum/#!searchin/search-guard/ldap|sort:relevance/search-guard/VLdvduqnDqQ/TFSvmAAhBgAJ) had same problems without the nullpointexception.

Elasticsearch LOG in debug mode: 
[elasticsearch.txt](https://github.com/floragunncom/search-guard/files/670450/elasticsearch.txt)
