### ISSUE TITLE
How host authentication works?

### ISSUE THREAD

**Issue by shkrid** [floragunncom/search-guard#303]
Please, explain me how host authentication works.

Authentication via username password (admin/admin) works, without it - no.
client ip - 172.30.0.3

@floragunncom 
#214 

I have following config but host authentication does not work:
-----------------------
sg_roles_mapping.yml
```
sg_role_starfleet:
  backendroles:
    - starfleet
    - captains
    - defectors
    - 'cn=ldaprole,ou=groups,dc=example,dc=com'
  hosts:
    - "*.starfleetintranet.com"
  users:
    - worf

sg_role_starfleet_captains:
  backendroles:
    - captains

sg_role_klingons1:
  backendroles:
    - klingon
  hosts:
    - "*.klingongov.kli"
  users:
    - worf

sg_logstash:
  users:
    - logstash
    
sg_kibana_server:
  users:
    - kibanaserver
    
sg_kibana:
  users:
    - kibanaro

sg_all_access:
  users:
    - admin
  hosts:
    - 172.30.0.3
    
sg_public:
  users:
    - '*'
    
sg_readall:
  users:
    - readall
    - riker
    - troid
    
sg_readonly_dlsfls:
  users:
    - dlsflsuser
    
sg_kibana_testindex:
  users:
    - test

sg_own_index:
  users:
    - '*'
```

sg_config.yml
```
searchguard:
  dynamic:
    http:
      anonymous_auth_enabled: false
      xff:
        enabled: true
        internalProxies: '.*' # trust all internal proxies, regex pattern
        remoteIpHeader:  'x-forwarded-for'
        proxiesHeader:   'x-forwarded-by'
        trustedProxies: '.*' 
    authc:
      basic_internal_auth_domain: 
        enabled: true
        order: 3
        http_authenticator:
          type: basic
          challenge: true
        authentication_backend:
          type: internal
      proxy_auth_domain:
        enabled: false
        order: 2
        http_authenticator:
          type: proxy
          challenge: false
          config:
            user_header: "x-proxy-user"
            roles_header: "x-proxy-roles"
        authentication_backend:
          type: noop
      host_auth_domain:
        enabled: false
        order: 1
        http_authenticator:
          type: host #DEPRECATED, will be removed in a future version
          challenge: false
        authentication_backend:
          type: internal
```

 http curl client:
```
/usr/src/app # ip addr | grep global
    inet 172.30.0.3/16 scope global eth0

/usr/src/app # curl -v 'http://elasticsearch:9200/_searchguard/authinfo?pretty=true' -u admin:admin
*   Trying 172.30.0.2...
* TCP_NODELAY set
* Connected to elasticsearch (172.30.0.2) port 9200 (#0)
* Server auth using Basic with user 'admin'
> GET /_searchguard/authinfo?pretty=true HTTP/1.1
> Host: elasticsearch:9200
> Authorization: Basic YWRtaW46YWRtaW4=
> User-Agent: curl/7.52.1
> Accept: */*
>
< HTTP/1.1 200 OK
< access-control-allow-credentials: true
< content-type: application/json; charset=UTF-8
< content-length: 318
<
{
  "user" : "User [name=admin, roles=[]]",
  "user_name" : "admin",
  "user_requested_tenant" : null,
  "remote_address" : "172.30.0.3:50908",
  "sg_roles" : [
    "sg_all_access",
    "sg_own_index",
    "sg_public"
  ],
  "sg_tenants" : {
    "admin" : true
  },
  "principal" : null,
  "peer_certificates" : "0"
}
* Curl_http_done: called premature == 0
* Connection #0 to host elasticsearch left intact



/usr/src/app # curl -v 'http://elasticsearch:9200/_searchguard/authinfo?pretty=true'
*   Trying 172.30.0.2...
* TCP_NODELAY set
* Connected to elasticsearch (172.30.0.2) port 9200 (#0)
> GET /_searchguard/authinfo?pretty=true HTTP/1.1
> Host: elasticsearch:9200
> User-Agent: curl/7.52.1
> Accept: */*
>
< HTTP/1.1 401 Unauthorized
< access-control-allow-credentials: true
< WWW-Authenticate: Basic realm="Search Guard"
< content-type: text/plain; charset=UTF-8
< content-length: 12
<
* Curl_http_done: called premature == 0
* Connection #0 to host elasticsearch left intact
```

Elastisearch debug logs:
```
es1_1           | [2017-02-24T14:06:43,493][DEBUG][c.f.s.a.BackendRegistry  ] Try to extract auth creds from http basic
es1_1           | [2017-02-24T14:06:43,500][DEBUG][c.f.s.a.BackendRegistry  ] User 'admin' is in cache? false (cache size: 0)
es1_1           | [2017-02-24T14:06:43,517][DEBUG][c.f.s.a.BackendRegistry  ] admin not cached, return from internal backend directly
es1_1           | [2017-02-24T14:06:43,861][DEBUG][c.f.s.a.BackendRegistry  ] User 'User [name=admin, roles=[]]' is authenticated
es1_1           | [2017-02-24T14:06:43,861][DEBUG][c.f.s.a.BackendRegistry  ] sg_tenant 'null'

es1_1           | [2017-02-24T14:06:49,903][DEBUG][c.f.s.a.BackendRegistry  ] Try to extract auth creds from http basic
```
