### ISSUE TITLE
Can't initialize searchguard in docker compose

### ISSUE THREAD

**Issue by gonechar** [floragunncom/search-guard#333]
If something written incorrect - sorry for my english...
I successfully installed and initialized searchguard without docker, but i can't do it via docker-compose.
I use CentOS Linux release 7.2.1511 (Core), elasticsearch 5.2.2
I created docker image from elasticsearch official docker image.
my Dockerfile:

```
FROM docker.elastic.co/elasticsearch/elasticsearch:5.2.2
USER root

ADD search-guard-5-5.2.2-12.zip /usr/share/elasticsearch/bin/

ADD search-guard-ssl-5.2.2.zip /usr/share/elasticsearch
RUN unzip search-guard-ssl-es-5.2.2.zip
RUN cd /usr/share/elasticsearch/search-guard-ssl-es-5.2.2/example-pki-scripts/ && /usr/share/elasticsearch/search-guard-ssl-es-5.2.2/example-pki-scripts/example.sh \
&& cp /usr/share/elasticsearch/search-guard-ssl-es-5.2.2/example-pki-scripts/kirk-keystore.jks /usr/share/elasticsearch/config \
&& cp /usr/share/elasticsearch/search-guard-ssl-es-5.2.2/example-pki-scripts/node-0-keystore.jks /usr/share/elasticsearch/config \
&& cp /usr/share/elasticsearch/search-guard-ssl-es-5.2.2/example-pki-scripts/node-1-keystore.jks /usr/share/elasticsearch/config \
&& cp /usr/share/elasticsearch/search-guard-ssl-es-5.2.2/example-pki-scripts/truststore.jks /usr/share/elasticsearch/config

RUN bin/elasticsearch-plugin install file:///usr/share/elasticsearch/bin/search-guard-5-5.2.2-12.zip


RUN chown -R elasticsearch:elasticsearch /usr/share/elasticsearch/

RUN rm -rf plugins/x-pack

RUN chmod +x \
/usr/share/elasticsearch/plugins/search-guard-5/tools/hash.sh \
/usr/share/elasticsearch/plugins/search-guard-5/tools/sgadmin.sh

USER elasticsearch
```

next i create my image with command:

```
docker build --tag=elasticsearch-sg-522 ./
```

my docker-compose.yml:

```
version: '2'
services:
  elasticsearch1:
    image: elasticsearch-sg-522
    container_name: elasticsearch1
    environment:
      cluster.name: "elasticsearch"
      node.name: "node-0"
      network.host: 0.0.0.0
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms8g -Xmx8g"
      searchguard.ssl.transport.keystore_filepath: "/usr/share/elasticsearch/config/node-0-keystore.jks"
      searchguard.ssl.http.keystore_filepath: "/usr/share/elasticsearch/config/node-0-keystore.jks"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 24g
    cap_add:
      - IPC_LOCK
    volumes:
      # Persist elasticsearch data to a volume
      - ./es/data/elastic1:/usr/share/elasticsearch/data
      - ./es/logs/elastic1:/usr/share/elasticsearch/logs
      #- ./es/config/kirk-keystore.jks:/usr/share/elasticsearch/config/kirk-keystore.jks
      #- ./es/config/node-0-keystore.jks:/usr/share/elasticsearch/config/node-0-keystore.jks
      #- ./es/config/truststore.jks:/usr/share/elasticsearch/config/truststore.jks

      - ./es/config/sg_action_groups.yml:/usr/share/elasticsearch/config/sg_action_groups.yml
      - ./es/config/sg_config.yml:/usr/share/elasticsearch/config/sg_config.yml
      - ./es/config/sg_internal_users.yml:/usr/share/elasticsearch/config/sg_internal_users.yml
      - ./es/config/sg_roles_mapping.yml:/usr/share/elasticsearch/config/sg_roles_mapping.yml
      - ./es/config/sg_roles.yml:/usr/share/elasticsearch/config/sg_roles.yml
      - ./es/config/sg_action_groups.yml:/usr/share/elasticsearch/plugins/search-guard-5/sgconfig/sg_action_groups.yml
      - ./es/config/sg_config.yml:/usr/share/elasticsearch/plugins/search-guard-5/sgconfig/sg_config.yml
      - ./es/config/sg_internal_users.yml:/usr/share/elasticsearch/plugins/search-guard-5/sgconfig/sg_internal_users.yml
      - ./es/config/sg_roles_mapping.yml:/usr/share/elasticsearch/plugins/search-guard-5/sgconfig/sg_roles_mapping.yml
      - ./es/config/sg_roles.yml:/usr/share/elasticsearch/plugins/search-guard-5/sgconfig/sg_roles.yml
      - ./es/config/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
      # Extra ES configuration options
      - ./es/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 0.0.0.0:9200:9200
      - 0.0.0.0:9300:9300
    logging:
      driver: "json-file"
    networks:
      - elknet-test


networks:
  elknet-test:
      driver: bridge
```

next i mount elasticsearch.yml:
```
searchguard.ssl.transport.enabled: "true"
searchguard.ssl.transport.keystore_filepath: "/usr/share/elasticsearch/config/node-0-keystore.jks"
searchguard.ssl.transport.keystore_password: "changeit"
searchguard.ssl.transport.truststore_filepath: "/usr/share/elasticsearch/config/truststore.jks"
searchguard.ssl.transport.truststore_password: "changeit"
searchguard.ssl.http.clientauth_mode: "NONE"
searchguard.ssl.transport.resolve_hostname: "true"
searchguard.ssl.transport.enforce_hostname_verification: "false"

searchguard.ssl.http.enabled: "false"
searchguard.ssl.http.keystore_filepath: "/usr/share/elasticsearch/config/node-0-keystore.jks"
searchguard.ssl.http.keystore_password: "changeit"
searchguard.ssl.http.truststore_filepath: "/usr/share/elasticsearch/config/truststore.jks"
searchguard.ssl.http.truststore_password: "changeit"
searchguard.authcz.admin_dn: "CN=kirk,OU=client,O=client,L=Test,C=DE"
```

next i execute command ``` docker-compose up ```

I tried 2 variants:
1) if i try to initialize searchguard via docker ssh i get message:
```
Cannot retrieve cluster state due to: None of the configured nodes are available: [{#transport#-1}{wXXGGDEVQyGzlS2Y8p0xIg}{localhost}{127.0.0.1:9300}]. This is not an error, will keep on trying ...
```
 i connect into docker container via command: ```docker exec -it e348d52a8bc3 bash```
next i execute comman: 
```
/usr/share/elasticsearch/plugins/search-guard-5/tools/sgadmin.sh  -ks /usr/share/elasticsearch/search-guard-ssl-es-5.2.2/example-pki-scripts/kirk-keystore.jks  -ts /usr/share/elasticsearch/search-guard-ssl-es-5.2.2/example-pki-scripts/truststore.jks  -nhnv
```

logs of elasticssearch says:

```
[ERROR][c.f.s.t.SearchGuardRequestHandler] Cannot authenticate null
```

2) if i try to initialize searchguard from OS i got other errors 
(i hoped that docker could proxy into container and it would save me) 

```
/home/elasticsearch/elasticsearch-5.2.2/plugins/search-guard-5/tools/sgadmin.sh -ks /home/elasticsearch/elasticsearch-5.2.2/config/kirk-keystore.jks -ts /home/elasticsearch/elasticsearch-5.2.2/config/truststore.jks
```

got errors:
```
ERROR com.floragunn.searchguard.ssl.transport.SearchGuardSSLNettyTransport - SSL Problem General SSLEngine problem
....
....
java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
```
this variant looks like incorrect because i use keys generated by another examplar of searchguard ssl
