### ISSUE TITLE
kibana multi-tenancy modifying Global and Private parameters

### ISSUE THREAD

**Issue by faxm0dem** [floragunncom/search-guard#336]
Hi,

Using SG12 zip using ES 5.3.2 (RPM) and Kibana 5.3.2 (RPM).
I wanted to change the default behaviour of the Global tenant to be RO by using the following `sg_roles.yaml` content:

```yaml
sg_human_resources:
  cluster:
    ...
  indices:
    ...
  tenants:
    Global: RO
    Private: RW
```

The results are quite disastrous :-)
Plenty of 500 errors in kibana when switching to any tenant and other errors.

I removed the setting, and added a new tenant and things improved, but I still have errors and my new tenant doesn't appear in the list. Maybe the searchguard index is corrupted?
