### ISSUE TITLE
Roles issue: no permissions for indices:data/read/mget

### ISSUE THREAD

**Issue by Passpes** [floragunncom/search-guard#341]
Hi I'm using searchguard 5 with Fluentd - ES 5.2.2 -kibana
and having some problems with roles, so I created a new index and trying to search it using a user x and here's my config for that:
```
sg_tralala:
    cluster:
      - CLUSTER_COMPOSITE_OPS_RO
    indices:
      'logstash-tralala-*':
        '*':
         - READ
         - indices:admin/mappings/fields/get*
      '?kibana-tralala':
        '*':
          - ALL
```
and then I got this error on kibana:
`Courier Fetch Error: unhandled courier request error: [security_exception] no permissions for indices:data/read/mget`

and this error on ES logs:

`No perm match for User [name=laghao, roles=[]] [IndexType [index=.kibana-tralala,type=index-pattern]] [Action [indices:data/read/mget]] [RolesChecked [tralala]]`
