### ISSUE TITLE
Searchguard denied indices that has date math name

### ISSUE THREAD

**Issue by netanel246** [floragunncom/search-guard#374]
ES Version: 5.2.2
Search Guard Version: 5.2.2-15
JVM : Java 8
OS: Redhat 7
Nodes: 3 Master, Data nodes and 1 Client node

Search Guard denied this index name: <users-{now/d}> ,
although we have got the name users-* in the sg_roles.yml
When we add this pattern  <users-* it works well.
I think that searchguard checks the index name before elastic evaluate the "real" name.
Elastic Date Math:
[https://www.elastic.co/guide/en/elasticsearch/reference/current/date-math-index-names.html#date-math-index-names](url)

**Comment by floragunncom** [comment]
Do you have an existing index where &lt;users-{now/d}&gt; should match? I can reproduce it only if there is no such index.

**Comment by Zuckonit** [comment]
may be a related question, how could we use regex (exclude '*') in indices within sg_roles.yml, like '\d', for example:

```
role_application_bteye_ddB4kBOJFO8rsgUy:
  cluster:
  - indices:admin/get/my_index_\d{1}\d{2}
  - CLUSTER_COMPOSITE_OPS
  indices:
    my_index_\d{1}\d{2}:
      '*':
      - READ
```

is above example ok?
