### ISSUE TITLE
More than one action request filter is not taken into account - It Should be declared as a list- es 1.6

### ISSUE THREAD

**Issue by YonoloX** [floragunncom/search-guard#39]
Hello,

I observed a very strange behavior when I add more than one action request filter, for example with the following yml configuration : 
```yml
searchguard.authentication.settingsdb.user.admin: secret
searchguard.authentication.settingsdb.user.yonolox: vulcan
searchguard.authentication.settingsdb.user.pixis: neverland
searchguard.authentication.settingsdb.user.test: test

searchguard.authentication.authorization.settingsdb.roles.admin: ["root"]
searchguard.authentication.authorization.settingsdb.roles.yonolox: ["superuser"]
searchguard.authentication.authorization.settingsdb.roles.pixis: ["guest"]
searchguard.authentication.authorization.settingsdb.roles.test: ["hidden"]

searchguard.actionrequestfilter.names: ["readonly"]
searchguard.actionrequestfilter.readonly.allowed_actions: ["indices:data/read/*", "*monitor*", "indices:admin/exists"]
searchguard.actionrequestfilter.readonly.forbidden_actions: ["cluster:admin*", "indices:admin*", "indices:data/write*"]

searchguard.actionrequestfilter.names: ["nonaccessible"]
searchguard.actionrequestfilter.nonaccessible.allowed_actions: []
searchguard.actionrequestfilter.nonaccessible.forbidden_actions: ["cluster:*", "indices:*"]
 ```
and the searchguard indice : 

```curl
curl -XPUT 'http://localhost:9200/searchguard/ac/ac' -d '{
"acl": [
    {
      "__Comment__": "Default is to execute all filters",
      "filters_bypass": [],
      "filters_execute": ["actionrequestfilter.readonly"]
    },
    {
      "__Comment__": "Any authenticated user do anything on the public index - no filter will be executed",
      "indices": ["public"],
      "filters_bypass": ["*"],
      "filters_execute": []
    },
    {
      "__Comment__": "This means any user with the role starfleet or command can do anything with the starfleetinfos index",
      "roles" : ["superuser"],
      "indices": ["twitter"],
      "filters_bypass": ["*"],
      "filters_execute": []
    },
    {
      "__Comment__": "This means that every requestor (regardless of the requestors hostname and username) which has the root role can do anything",
      "roles": ["root"],
      "filters_bypass": ["*"],
      "filters_execute": []
    },
    {
      "__Comment__": "This means that the user michaeljackson can do anything on index popstuff.",
      "roles": ["guest"],
      "filters_bypass": [],
      "filters_execute": ["actionrequestfilter.readonly"]
    },
    {
      "__Comment__": "This means that for the user spock on index popstuff only the actionrequestfilter.readonly will be executed, no other",
      "users": ["pixis"],
      "indices": ["twitter"],
      "filters_bypass": [],
      "filters_execute": ["actionrequestfilter.nonaccessible"]
    }
  ]}
}'
```

I find that only the latest defined action request is taken into account, this means that only nonaccessible is applied and readonly is discarded (same happens when I change the order; readonly becomes applied and nonaccessible  is no more applied)

Could you correct me if I'm missing something ?
Thanks in advance!

**Comment by YonoloX** [comment]
hello,
In fact it takes more than one action request filter if these are declared as a list : 

```yaml
searchguard.actionrequestfilter.names: ["readonly", "nonaccessible"]
searchguard.actionrequestfilter.readonly.allowed_actions: ["indices:data/read/*", "*monitor*", "indices:admin/exists"]
searchguard.actionrequestfilter.readonly.forbidden_actions: ["cluster:admin*", "indices:admin*", "indices:data/write*"]
searchguard.actionrequestfilter.nonaccessible.allowed_actions: []
searchguard.actionrequestfilter.nonaccessible.forbidden_actions: ["cluster:*", "indices:*"]
```
I think you can close the issue.

Thanks !
