### ISSUE TITLE
Authentication finally failed for null

### ISSUE THREAD

**Issue by wangxiangyu** [floragunncom/search-guard#408]
hi,
I am using 5.4.3 and use `Proxy Authentication`
sg_config.yml
```
    authc:
      proxy_auth_domain:
        enabled: true
        order: 0
        http_authenticator:
          type: proxy
          challenge: false
          config:
            user_header: "x-proxy-user"
            roles_header: "x-proxy-roles"
        authentication_backend:
          type: noop
```
sg_roles_mapping.yml
```
sg_all_access:
  users:
    - admin
  backendroles:
    - adminrole
```
But when I send request to es( ssl is disabled), `auth is failed`：
![image](https://user-images.githubusercontent.com/3917969/32778242-ca7fa672-c8fe-11e7-898d-5161535967fc.png)

ES log：
```
[2017-11-14T19:43:37,272][WARN ][c.f.s.a.BackendRegistry  ] Authentication finally failed for null
```
Is there something wrong or any mistake ? Thank you
