### ISSUE TITLE
Permission denied when using elasticsearch curator

### ISSUE THREAD

**Issue by mikn** [floragunncom/search-guard#428]
Running Searchguard-6-17.beta1 on Elasticsearch 6.0.0, having 7 nodes I have created a couple of different custom roles, one of which is for Curator.
Role looks like this:
```yaml
sg_curator:
  readonly: true
  cluster:
  - "CLUSTER_MONITOR"
  - "INDICES_MONITOR"
  indicies:
    logstash-*:
      '*':
      - "DELETE"
```
Role binding like this:
```yaml
sg_curator:
  readonly: true
  users:
  - "curator"
```
But I still get errors like this:
```json
{"@timestamp": "2017-12-17T11:43:46.294Z", "function": "log_request_fail", "linenum": 97, "loglevel": "WARNING", "message": "GET https://log-store-elasticsearch.services.svc.cluster.local:9200/_all/_settings?expand_wildcards=open%2Cclosed [status:403 request:0.002s]", "name": "elasticsearch"}
{"@timestamp": "2017-12-17T11:26:41.614Z", "function": "run", "linenum": 184, "loglevel": "ERROR", "message": "Failed to complete action: delete_indices.  <class 'curator.exceptions.FailedExecution'>: Failed to get indices. Error: TransportError(403, 'security_exception', 'no permissions for [indices:monitor/settings/get] and User [name=curator, roles=[], requestedTenant=null, attributes={}]')", "name": "curator.cli"}
```
I have also tried assigning the `sg_curator` unlimited permissions, and it still does not work. I have also tried assigning the curator user to the `sg_all_access` group... In which case it actually works, but I do not know why.

**Comment by floragunncom** [comment]
try

<pre>
sg_curator:
  cluster:
  - "CLUSTER_MONITOR"
  - "CLUSTER_COMPOSITE_OPS"
  indicies:
    logstash-*:
      '*':
      - "DELETE"
      - INDICES_MONITOR
</pre>

**Comment by floragunncom** [comment]
pls post also the output of the /_searchguard/authinfo?pretty endpoint when logged in with "curator" user

**Comment by mikn** [comment]
The permissions you suggested seems to have worked. Thank you! I'll close it tomorrow if it still works when deleting indices. :)

**Comment by floragunncom** [comment]
pls leave this open for now because we need to update the docs

**Comment by mikn** [comment]
I can confirm they're working. Thank you!

**Comment by zakkg3** [comment]
Just if anyone its here trying to apply the @floragunncom comment, note "indicies" should be indices, like this:

```
sg_curator:
  cluster:
  - "CLUSTER_MONITOR"
  - "CLUSTER_COMPOSITE_OPS"
  indices:
    logstash-*:
      '*':
      - "DELETE"
      - INDICES_MONITOR
```
