### ISSUE TITLE
SG not creating attributes

### ISSUE THREAD

**Issue by YairHalberstadt** [floragunncom/search-guard#459]
I have the following two roles in my sg_roles.yml file

```
company_admin:
  cluster:
    - ALL
  indices:
    '${attr.internal.company}*':
      '*':
        - ALL

kibana_user:
  cluster:
    - MONITOR
    - CRUD
  indices:
    '?kibana':
      '*':
        - ALL
```

I have the following mappings in my sg_roles_mapping.yml file

```
company_admin:
    backendroles:
        - company_admin
    host:
        - "*"

kibana_user:
    backendroles:
        - kibana_user
    host:
        - "*"
```

I have the following user in my sg_internal_users.yml file

```
google:
  hash: '$2y$12$UPu5orpoef8.u7/bj.23lOst5mqKPj1A6opQIOUIMaaYDIHJL1ecm' #elastic
  roles:
  - company_admin
  - kibana_user
  attributes:
    company: google
```

Now when I try to access the index "google" I get an error:

> no permissions for [indices:data/read/search] and User [name=google, roles=[kibana_user, company_admin], requestedTenant=null]"

By process of elimination, I discover this issue only occurs when I create index level permissions based on a custom attribute.

So I run this curl: 
`curl -XGET "http://localhost:9200/_searchguard/authinfo" -u google -Ss -k`

which should get the properties of "google". The response is:

> {"user":"User [name=google, roles=[kibana_user, company_admin], requestedTenant=null]","user_name":"google","user_requested_tenant":null,"remote_address":"172.18.0.1:59930","backend_roles":["kibana_user","company_admin"],"custom_attribute_names":[],"sg_roles":["company_admin","kibana_user"],"sg_tenants":{"google":true},"principal":null,"peer_certificates":"0"}

So custom_attribute_names is empty.

Why would this be the case?

**Comment by floragunncom** [comment]
Can you pls tell us your elasticsearch and Search Guard version and post the contents of sg_config.yml ?

**Comment by jochenkressin** [comment]
The custom attributes for the internal user database was added in 6.x-21. Maybe you use an older 6.x-20 Search Guard version?

**Comment by YairHalberstadt** [comment]
"version":"6.1.1-20.1"

**Comment by YairHalberstadt** [comment]
sg_config.yml:

```
searchguard:
  dynamic:
    authc:
      basic_internal_auth:
        enabled: true
        order: 1
        http_authenticator:
          type: basic
          challenge: true
        authentication_backend:
          type: internal
```

**Comment by YairHalberstadt** [comment]
@jochenkressin : Looks like that was it I guess then. I will try and update the version.

**Comment by YairHalberstadt** [comment]
I have updated the version to 6.1.1-21.0, and the curl now shows 

> "custom_attribute_names":["attr.internal.company"]

On start-up the company is indeed displayed as "google" on the console.
However I still am getting the same error when I try to search the "google" index.
Note that is if I change sg_roles.yml to:

```
company_admin:
  cluster:
    - ALL
  indices:
    '${user_name}*':
      '*':
        - ALL
```

It works fine. So it just doesn't seem to be playing nicely with `${attr.internal.company}` for some reason
