### ISSUE TITLE
Multitenancy error 

### ISSUE THREAD

**Issue by zqc0512** [floragunncom/search-guard#469]
system:centos 7.3 x86_64
elasticsearch:5.6.8 with x-pack monitoring
search-guard: 5.6.8 

Multitenancy error with this:
Active tenant: Global
**It seems that the Multitenancy module is not installed on your Elasticsearch cluster, or it is disabled. Multitenancy will not work, please check your installation.**

in es i can't show  .kiban_admin_tenant index.
![image](https://user-images.githubusercontent.com/25192261/38223491-c4d50572-371d-11e8-9391-52724cb9cca8.png)

**Comment by zqc0512** [comment]
i also set in the sg_config.yml file
```
searchguard:
  dynamic:
    kibana:
      multitenancy_enabled: true
      server_username: "admin"
      do_not_fail_on_forbidden: true
      index: ".kibana"
```
