### ISSUE TITLE
OpenID 

### ISSUE THREAD

**Issue by NocturnalShadow** [floragunncom/search-guard#472]
I am trying to integrate Kibana and Keycloak. Official doc says that Search Guard Enterprise Edition has a feature of "OpenID integration", so we decided to give it a try with Trial License and to buy Enterprise if it works out.

I am on Windows 10 machine, have Elasticsearch 6.2.2 and Kibana 6.2.2 set up. I've installed Search Guard plugin 6.2.2-22 on both Elastisearch and Kibana. I did a demo setup running all the necessary script and get them working with basic authentication.

Further, I've changed the configuration to use OpenID as described [here ](https://docs.search-guard.com/latest/openid-json-web-keys).
I have the following config files:
**elasticsearch.yml**
```
http.port: 9200

######## Start Search Guard Demo Configuration ########
# WARNING: revise all the lines below before you go into production
searchguard.ssl.transport.pemcert_filepath: esnode.pem
searchguard.ssl.transport.pemkey_filepath: esnode-key.pem
searchguard.ssl.transport.pemtrustedcas_filepath: root-ca.pem
searchguard.ssl.transport.enforce_hostname_verification: false
searchguard.ssl.http.enabled: true
searchguard.ssl.http.pemcert_filepath: esnode.pem
searchguard.ssl.http.pemkey_filepath: esnode-key.pem
searchguard.ssl.http.pemtrustedcas_filepath: root-ca.pem
searchguard.allow_unsafe_democertificates: true
searchguard.allow_default_init_sgindex: true
searchguard.authcz.admin_dn:
  - CN=kirk,OU=client,O=client,L=test, C=de

searchguard.audit.type: internal_elasticsearch
searchguard.enable_snapshot_restore_privilege: true
searchguard.check_snapshot_restore_write_privileges: true
searchguard.restapi.roles_enabled: ["sg_all_access"]
cluster.name: searchguard_demo
network.host: 0.0.0.0
discovery.zen.minimum_master_nodes: 1
node.max_local_storage_nodes: 3
######## End Search Guard Demo Configuration ########

```

**kibana.yml**
```
# Use HTTPS instead of HTTP
elasticsearch.url: "https://localhost:9200"

# Configure the Kibana internal server user
elasticsearch.username: "admin"
elasticsearch.password: "admin"

# Disable SSL verification because we use self-signed demo certificates
elasticsearch.ssl.verificationMode: none

# Whitelist the Search Guard Multi Tenancy Header
elasticsearch.requestHeadersWhitelist: [ "Authorization" ]

searchguard.basicauth.enabled: false
```
Finally, **sg_config.yml**
```
searchguard:
  dynamic:
    http:
      anonymous_auth_enabled: false
      xff:
        enabled: false
        internalProxies: '192\.168\.0\.10|192\.168\.0\.11' # regex pattern
        #internalProxies: '.*' # trust all internal proxies, regex pattern
        remoteIpHeader:  'x-forwarded-for'
        proxiesHeader:   'x-forwarded-by'
        #trustedProxies: '.*' # trust all external proxies, regex pattern
    authc:
      openid_auth_domain:
        enabled: true
        order: 0
        http_authenticator:
          type: openid
          challenge: false
          config:
            jwt_header: "Authorization"
            jwt_url_parameter: null
            roles_key: roles
            subject_key: preferred_username
            openid_connect_url: https://keycloak.mycompany.com/realms/master/.well-known/openid-configuration
        authentication_backend:
          type: noop
      basic_internal_auth_domain: 
        enabled: false
        order: 1
        http_authenticator:
          type: basic
          challenge: false
        authentication_backend:
          type: intern
    authz:    
```

Then I restart Elasticsearch and Kibana.
**Expected behaviour:** 
When I go to http://localhost:5601/ I get redirected to Keycloak https://keycloak.mycompany.com/auth (or whatever is correct), enter my credentials, get redirected back and get signed on.
**Actual behaviour:**
When I go to http://localhost:5601/ alert pops out in my browser asking for Elasticsearch credentials. Same as if I got to https://localhost:9200.

Kibana -> Search Guard -> Lisence & System info shows the following modules active:
![untitled](https://user-images.githubusercontent.com/25293920/38305742-a553971e-3816-11e8-8a73-6b96982f3fb2.JPG)

Kibana ->Search Guard -> Authentication & Authorisation (with "S" by some reason) shows the following picture:
![auth](https://user-images.githubusercontent.com/25293920/38306027-cf68b128-3817-11e8-9c50-d42331131474.gif)

It seams that OpenID integration is missing enables Basic Authentication instead.

Please, fix this or tell me what I'm doing wrong. If we are not able to integrate Search Guard with Keycloak we will have no choice but to go and search for another solution...

P.S. There I would have gladly used 6.2.3 version instead of 6.2.2 but there are no 6.2.3 Search Guard plugin for Kibana (only 6.2.2) and it is not allowed to mix 6.2.2 with 6.2.3. Although, [wiki](https://github.com/floragunncom/search-guard/wiki) references 6.2.3 for Kibana but I can not find it anywhere.
