### ISSUE TITLE
change demo user password don't work

### ISSUE THREAD

**Issue by ZMMWMY** [floragunncom/search-guard#478]
version:
es:6.2.3     search-guard:6.2.3
1. i want change admin password , use hash.sh generate password 12345
2. vi sg_internal_users.yml
3.use sgadmin.sh update password  but it don't work
show logs 
```
Will connect to localhost:9300 ... done
Elasticsearch Version: 6.2.3
Search Guard Version: 6.2.3-22.0
Connected as CN=sgadmin,OU=client,O=client,L=Test,C=DE
Contacting elasticsearch cluster 'elasticsearch' and wait for YELLOW clusterstate ...
Clustername: docker-cluster
Clusterstate: GREEN
Number of nodes: 1
Number of data nodes: 1
searchguard index already exists, so we do not need to create one.
Populate config from /usr/share/elasticsearch/config/sg/
Will update 'sg/config' with /usr/share/elasticsearch/config/sg/sg_config.yml 
   SUCC: Configuration for 'config' created or updated
Will update 'sg/roles' with /usr/share/elasticsearch/config/sg/sg_roles.yml 
   SUCC: Configuration for 'roles' created or updated
Will update 'sg/rolesmapping' with /usr/share/elasticsearch/config/sg/sg_roles_mapping.yml 
   SUCC: Configuration for 'rolesmapping' created or updated
Will update 'sg/internalusers' with /usr/share/elasticsearch/config/sg/sg_internal_users.yml 
   SUCC: Configuration for 'internalusers' created or updated
Will update 'sg/actiongroups' with /usr/share/elasticsearch/config/sg/sg_action_groups.yml 
   SUCC: Configuration for 'actiongroups' created or updated
```

**Comment by floragunncom** [comment]
Thats far to few informations for a bug report. Pls post your sg_internal_users.yml, your sgadmin command and how you test for that the password is changed.

**Comment by ZMMWMY** [comment]
my mistake
case i use docker,i copy sgconfig volumes in my Dockerfile
```
FROM elasticsearch:latest
ADD search-guard/search-guard-6-6.2.3-22.0.zip /usr/share/elasticsearch/temp/
COPY config/sg/ config/sg/
COPY bin/ bin/
RUN elasticsearch-plugin install -b file:///usr/share/elasticsearch/temp/search-guard-6-6.2.3-22.0.zip  \
	&& chmod +x plugins/search-guard-6/tools/*.sh \
	&& chown -R elasticsearch config/sg/ \
	&& chmod -R go= config/sg/
```
but i was wrong,i should volumes this .
i change it and its work
```
version: '2'
services:
  elasticsearch:
    build:
      context: elastic/
    volumes: 
      - /root/elk-6.2.3/elastic/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /root/elk-6.2.3/elastic/data/:/usr/share/elasticsearch/data/
      - /root/elk-6.2.3/elastic/logs/:/usr/share/elasticsearch/logs/
      - /root/elk-6.2.3/elastic/config/sg/users/:/usr/share/elasticsearch/config/sg/users/
```
thank you
