### ISSUE TITLE
sgadmin fails and blocks debugging through rest API 

### ISSUE THREAD

**Issue by opsj** [floragunncom/search-guard#484]
* Search Guard and Elasticsearch version: SG Version: v6, ES client version: 6.1.2
* JVM version and operating system version: `openjdk version "1.8.0_151"` and RHEL 7
* Number of nodes in your cluster: 1
* Description of the bug: When running the following command:
```
./sgadmin.sh -f /etc/elasticsearch/sg_config.yml -nhnv -cn elasticsearch-dev -ts /etc/elasticsearch/ssl/elasticsearch.truststore.jks -tspass xxxx -ks /etc/elasticsearch/ssl/dev-elasticsearch-admin.jks -kspass xxxxx -ksalias dev-elasticsearch-admin
```

Which hangs on the following output: 
```
WARNING: JAVA_HOME not set, will use /bin/java
Search Guard Admin v6
Will connect to localhost:9300 ... done
Elasticsearch Version: 6.1.2
Search Guard Version: 6.1.2-22.0
Connected as CN=dev-elasticsearch-admin,xxxxxx
Contacting elasticsearch cluster 'elasticsearch-dev' and wait for YELLOW clusterstate ...
```

Here is my elasticsearch.yml file:
```
node.name: node1

cluster.name: elasticsearch-dev
node.master: true
node.data: true
path.data: /data
path.logs: /logs
network.host: [ _site_ , _local_ ]

discovery.zen.ping.unicast.hosts: [
"node1"
]

discovery.zen.minimum_master_nodes: 1
gateway.expected_nodes: 1
gateway.recover_after_time: 20m
gateway.recover_after_nodes: 1

# Search Guard Configs

searchguard.enterprise_modules_enabled: false
searchguard.ssl.http.enabled: false

searchguard.ssl.transport.keystore_type: JKS
searchguard.ssl.transport.keystore_filepath: /etc/elasticsearch/ssl/node1.jks
searchguard.ssl.transport.keystore_password: xxxxx
searchguard.ssl.transport.truststore_type: JKS
searchguard.ssl.transport.truststore_filepath: /etc/elasticsearch/ssl/elasticsearch.truststore.jks
searchguard.ssl.transport.truststore_password: xxxxx
searchguard.ssl.transport.keystore_alias: xxxxxxx


searchguard.authcz.admin_dn:
  - "CN=dev-elasticsearch-admin,OU=xxx,O=xxxx,L=xxxx,ST=xxxx,C=US"

# Inter-node communication
searchguard.nodes_dn:
    - "CN=node1,OU=xxxx,O=xxxx,L=xxxx,S=xxxx,C=US"
```

Here is sg_config.yml:
```
searchguard:
  dynamic:
    authc:
      clientcert_auth_domain:
        http_enabled: false
        transport_enabled: true
        order: 1
        http_authenticator:
          type: clientcert
          config:
            username_attribute: cn #optional, if omitted DN becomes username
          challenge: false
        authentication_backend:
          type: noop
#    authz:
```

and finally, the diagnose.txt file:
```
Who am i:
{
  "whoami" : {
    "dn" : "CN=dev-elasticsearch-admin,......",
    "is_admin" : true,
    "is_authenticated" : true,
    "is_node_certificate_request" : false
  }
}License:
{
  "sg_license" : {
    "msgs" : [
      "No license required because enterprise modules not enabled."
    ],
    "license_required" : false
  },
  "modules" : { },
  "compatibility" : {
    "modules_mismatch" : false
  }
}ClusterHealthRequest:
{
  "cluster_name" : "elasticsearch-dev",
  "status" : "red",
  "timed_out" : false,
  "number_of_nodes" : 1,
  "number_of_data_nodes" : 1,
  "active_primary_shards" : 0,
  "active_shards" : 0,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 6,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue" : "0s",
  "task_max_waiting_in_queue_millis" : 0,
  "active_shards_percent" : "0.0%",
  "active_shards_percent_as_number" : 0.0
}
```

I see the cluster state is red, but am unable to use any sort of rest API from elasticserch to debug the issue because it will complain with this error:
```
Search Guard not initialized (SG11). See http://docs.search-guard.com/v6/sgadmin
```
