### ISSUE TITLE
Invalid license issue

### ISSUE THREAD

**Issue by iahmad-khan** [floragunncom/search-guard#490]
I am facing a strange issue here , after I uploaded the key to searchguard through kibana interface:

1. when i run sgadmin.sh , all the configuration is deleted
2. i have to put the license again through kibana interface , othervise it defaults to trial

```
docker exec 80 bin/init_sg.sh

Search Guard Admin v6
Will connect to localhost:9300 ... done
Elasticsearch Version: 6.2.1
Search Guard Version: 6.2.1-22.0
Connected as CN=kirk,OU=client,O=client,L=Test,C=DE
Contacting elasticsearch cluster 'elasticsearch' and wait for YELLOW clusterstate ...
Clustername: docker-cluster
Clusterstate: GREEN
Number of nodes: 5
Number of data nodes: 5
searchguard index already exists, so we do not need to create one.
Populate config from /usr/share/elasticsearch/config/sg
Will update 'sg/config' with config/sg/sg_config.yml 
   SUCC: Configuration for 'config' created or updated
Will update 'sg/roles' with config/sg/sg_roles.yml 
   SUCC: Configuration for 'roles' created or updated
Will update 'sg/rolesmapping' with config/sg/sg_roles_mapping.yml 
   SUCC: Configuration for 'rolesmapping' created or updated
Will update 'sg/internalusers' with config/sg/sg_internal_users.yml 
   SUCC: Configuration for 'internalusers' created or updated
Will update 'sg/actiongroups' with config/sg/sg_action_groups.yml 
   SUCC: Configuration for 'actiongroups' created or updated
Invalid license
Invalid license
Invalid license
Invalid license
Invalid license
Done with failures

```

sg_config file:

```
searchguard:
  dynamic:
    http:
      xff:
        enabled: false
    authc:
      basic_internal_auth_domain:
        http_authenticator:
          type: basic
        authentication_backend:
          type: intern

```
