### ISSUE TITLE
X-Pack Monitoring | Permission denied

### ISSUE THREAD

**Issue by NerdSec** [floragunncom/search-guard#491]
Hi,

While trying to identify the root cause of the issue reported [here](https://github.com/floragunncom/search-guard-kibana-plugin/issues/97), i tried to get X-Pack working using the demo installation script. Everything works fine initially however, I am getting an error while accessing the Monitoring plugin in Kibana.

![image](https://user-images.githubusercontent.com/26703835/39957069-175a9ba8-560a-11e8-8dcb-e69054a09dd4.png)

My sg_roles.yml is as follows:
```
sg_kibana_user:
  readonly: true
  cluster:
    - MONITOR
    - CLUSTER_COMPOSITE_OPS
  indices:
    '?kibana':
      '*':
        - MANAGE
        - INDEX
        - READ
        - DELETE
    '*':
      '*':
        - indices:data/read/field_caps*
    '?monitor*':
      '*':
        - INDICES_ALL

### X-Pack COMPATIBILITY
sg_xp_monitoring:
  readonly: true
  indices:
    '?monitor*':
      '*':
        - INDICES_ALL
```

My elasticsearch.yml configuration is as follows. I have excluded the demo conf added by the script:
```
xpack.monitoring.enabled: true

searchguard.enterprise_modules_enabled: false

xpack.monitoring.exporters:
  id1:
    type: http
    host: ["https://localhost:9200"]
    auth.username: admin
    auth.password: admin
    ssl:
      certificate: kirk.pem
      key: kirk-key.pem
  id2:
    type: http
    host: ["https://localhost:9200"]
    auth.username: kibanaro
    auth.password: kibanaro
    ssl:
      certificate: kirk.pem
      key: kirk-key.pem

```

**Note: I have not installed the Search Guard Kibana plugin**

Steps to reproduce the issue:

1. Install Elasticsearch and Kibana
2. Install x-pack on Elasticsearch & update Basic License.
3. Install search-guard and run the demo script (after modifying the sg_roles.yml).
4. Able to login to Kibana using basic auth prompted by browser.
5. Install x-pack on Kibana and open Kibana/Monitoring.

Regards,
N
