### ISSUE TITLE
Minimal sgconfig files to allow proper initialization

### ISSUE THREAD

**Issue by YouriT** [floragunncom/search-guard#502]
**SG Artefact**: com.floragunn:search-guard-6:6.2.4-22.1
**Elastic Version**: 6.2.4
**Java Version**: 1.8.0_171
**N° nodes**: 3
**Type**: Feature request / Doc request

Giving a shot to search-guard I realised there is no documentation about the minimal configuration that can be given to enable a full initialisation of SG.

Hence I'm trying step by step until finding the minimal config files that will enable SG to get to an initialised state without first adding the demo files.

I believe that documenting this minimum or adding it as a config example would be worth instead of adding plenty of boilerplate that not everyone will use.

My last failed attempt is the following:

**sg_action_groups.yml** is the one in the example config
**sg_config.yml**:
```yml
searchguard:
  dynamic:
    http:
      anonymous_auth_enabled: false
    authc:
      clientcert_auth_domain:
        http_enabled: true
        transport_enabled: true
        enabled: false
        order: 1
        http_authenticator:
          type: clientcert
          config:
            username_attribute: cn
          challenge: false
        authentication_backend:
          type: noop
```

**sg_internal_users.yml**:
```yml
{}
```
**sg_roles.yml**:
```yml
sg_all_access:
  readonly: true
  cluster:
    - UNLIMITED
  indices:
    '*':
      '*':
        - UNLIMITED
  tenants:
    admin_tenant: RW

# Read all, but no write permissions
sg_readall:
  readonly: true
  cluster:
    - CLUSTER_COMPOSITE_OPS_RO
  indices:
    '*':
      '*':
        - READ

# Read all and monitor, but no write permissions
sg_readall_and_monitor:
  cluster:
    - CLUSTER_MONITOR
    - CLUSTER_COMPOSITE_OPS_RO
  indices:
    '*':
      '*':
        - READ
```
**sg_roles_mapping.yml**:
```yml
sg_all_access:
  users:
    - youri
```

```
GET /_searchguard/health
{"message":"Not initialized","mode":"strict","status":"DOWN"}
```

As you can see I'm trying to have just the PKI auth with a role binding to `sg_all_access` for now (I know it's not the best, just trying around)

NB: Of course I tried the default files and it works like a charm.

**Comment by YouriT** [comment]
It seems to have to do with **sg_config.yml** from what I can see which seem to require the `basic_internal_auth_domain` to be enabled otherwise there it never gets initialised. Hence from deduction the very minimal **sg_config.yml** is the following:

```yml
searchguard:
  dynamic:
    http:
      anonymous_auth_enabled: false
      xff:
        enabled: false
    authc:
      basic_internal_auth_domain:
        http_enabled: true
        transport_enabled: true
        order: 1 # this can change of course
        http_authenticator:
          type: basic
          challenge: true
        authentication_backend:
          type: intern
    authz: {}
```
