### ISSUE TITLE
I can not config my roles with Index-level

### ISSUE THREAD

**Issue by anhnt094** [floragunncom/search-guard#505]
Hi everyone !
I am defining my custom roles and permissions with snippets:

In sg_roles.yml : 
```
sg_filebeat:
  cluster:
    - CLUSTER_MONITOR
    - CLUSTER_COMPOSITE_OPS
  indices:
    "*":
      '*':
        - READ
```
In sg_roles_mapping.yml : 
```
sg_filebeat:
  readonly: true
  backendroles:
    - mybackendrole
```
In sg_internal_users.yml : 
```
filebeat:
  hash: $2y$12$/oRmi.T9NBQg3A1xgOkArOKeI9CUsUSeisKJsut7OPcSFp/wBAXQ2
  roles:
    - mybackendrole
```
and here is my result:
![image](https://user-images.githubusercontent.com/34936548/41224528-e97c2c16-6d96-11e8-8d6e-c236a3e0cc02.png)
But when I change sg_roles.yml file to:
```
sg_filebeat:
  cluster:
    - CLUSTER_MONITOR
    - CLUSTER_COMPOSITE_OPS
  indices:
    "filebeat*":
      '*':
        - READ
```
and I have nothing:
![image](https://user-images.githubusercontent.com/34936548/41224728-5c7caf92-6d97-11e8-8b4a-9ecdc632424c.png)
![image](https://user-images.githubusercontent.com/34936548/41224750-6dd63da8-6d97-11e8-8948-f8188d79213e.png)
Can anybody help me? Thank you in advance.
