### ISSUE TITLE
Cannot connect to ldap elastic 6.3.0

### ISSUE THREAD

**Issue by iahmad-khan** [floragunncom/search-guard#514]
hi

I am posting it here because on the google group , I usually get no response:

Searchgaurd for elasticsearch 6.3.0

Error messege:

```
[2018-06-30T00:52:06,400][WARN ][c.f.s.a.BackendRegistry  ] Authentication finally failed for iahmad
[2018-06-30T00:52:06,608][WARN ][c.f.d.a.l.b.LDAPAuthorizationBackend] Unable to connect to ldapserver host:port due to java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "accessClassInPackage.com.sun.jndi.ldap.ext"). Try next.
```

Config:

```
ldap:
        enabled: true
        order: 2
        http_authenticator:
          type: basic
          challenge: true
        authentication_backend:
          type: ldap
          config:
            enable_ssl: false
            enable_start_tls: true
            enable_ssl_client_auth: false
            verify_hostnames: false
            hosts:
              - hostip:port
            bind_dn: null
            password: null
            userbase: 'ou=people,dc=domain,dc=com'
            usersearch: 'uid={0}'
            username_attribute: uid
```
this config works on other systems with ldap such as jenkins , ldap supports anon auth
