### ISSUE TITLE
Search Guard in Docker

### ISSUE THREAD

**Issue by Jrmyy** [floragunncom/search-guard#549]
Hi,

I have an issue with Search Guard and Docker. Thanks by advance.

Jeremy

* **Search Guard version:** 6.3.2-23.0
* **Elasticsearch version:** 6.3.2
* **Docker version:** Docker version 17.05.0-ce, build 89658be
* **Number of nodes:** 1
* **Host version:** Debian GNU/Linux 9
* **Description of the bug:** I have dockerized an ELK stack and I put SG to authenticate users. I have also a volume to synchronize Elasticsearch data so that the data is also on my host. But when I stop the Elasticsearch container and restart it, all my data is here but I cannot log in to Elasticsearch because I need to init Search Guard again. I would like to know if it is something expected or not ?
* **Steps to reproduce:**
1. Dockerize Elasticsearch using official image
2. Install SG plugin inside the container
3. Init SG inside the container
4. Try to log in
5. Restart the container
6. Try to log in again (you should have the error telling you that SG must be initialized.)

**Comment by tohtor** [comment]
Hi,
This simply can'y work. You have to init SG when you run the container.

The problem is that your elasticsearch data (i.e: your SG configuration) is wiped out ("replaced" or "hidden" is maybe a better term) when your container starts with a volume mapped to elasticsearch data

- When you run docker build with SG init: in your image, folder "/usr/share/elasticsearch/data" is filled with SG configuration
- When your container from your image with a volume: the volume on your host e.g "/home/jrmyy/es-data" is mounted to folder "/usr/share/elasticsearch/data" in your container so it's like your SG config isn't even here.

I hope you understand my explanations.

Regards

**Comment by tohtor** [comment]
I did some tests to verify what I was saying. So you have two options:
- If you use a "bind-mount", you have to do what I describe in previous answer (i.e: init SG when you first run the container)
- If you use a "volume" volume, you can init SG during docker build and then the data will be copied from the image in the volume if the volume is empty when you start the container.

**Comment by Jrmyy** [comment]
Hi,

Thanks for your answer. Actually, I do use bind-mounts for /usr/share/elasticsearch/data, and run the SG init at the first launch. But if I stop the container and start it again, I get the "Search Guard not initialized (SG11)", as if it had never been done. Other ES data don't change.

Here is my `elasticsearch` container in my docker compose file.

```
  elasticsearch:
    image: elasticsearch6.3.2-with-sg-plugin-installed-not-configured
    restart: always
    ports:
      - "9200:9200"
    environment:
      ES_JAVA_OPTS: "-Xmx1g -Xms1g"
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "./elasticsearch-data:/usr/share/elasticsearch/data"
      - "./analytics/elasticsearch/sg/:/usr/share/elasticsearch/config/sg"
      - "./analytics/elasticsearch/sg-certificates/:/usr/share/elasticsearch/config/sg-certificates"
      - "./analytics/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
```

As you can see, there are 4 bind-mount volumes: one for the data, one for the sg config (action groups, internal users, ...), one for the certifications and one for the ES config file.

Here is the `elasticsearch.yml` file:

```
---
## Default Elasticsearch configuration from elasticsearch-docker.
## from https://github.com/elastic/elasticsearch-docker/blob/master/build/elasticsearch/elasticsearch.yml
cluster.name: "docker-cluster"
network.host: 0.0.0.0

# minimum_master_nodes need to be explicitly set when bound on a public IP
# set to 1 to allow single node clusters
# Details: https://github.com/elastic/elasticsearch/pull/17288
discovery.zen.minimum_master_nodes: 1
searchguard.enterprise_modules_enabled: false
xpack.security.enabled: false
xpack.monitoring.enabled: true
xpack.monitoring.collection.enabled: true
```

Now, concerning the process:

1. I start the ES container
2. I generate my own certificates using tlstool
3. I init search guard with the following command : 
```
plugins/search-guard-6/tools/sgadmin.sh \
   -cd config/sg/ \
   -cacert config/sg-certificates/root-ca.pem \
   -cert config/sg-certificates/admin.pem \
   -key config/sg-certificates/admin.key \
   -keypass MYPASSWORD_GENERATED_BY_TLSTOOL \
   -nhnv \
   -icl
```
4. It works, I can authenticate
5. I run `docker-compose stop`
6. I run `docker-compose up`
7. It doesn't work, I get `Search Guard not initialized (SG11)`.

How come the SG config doesn't survive stops and starts ? Isn't it stored in an ES index (like Kibana config for instance) ?

**Comment by tohtor** [comment]
That's weird, I have something very similar for an Elastic stack. The only difference I can see is that I use a volume. A bind-mount should work too.

Extract from docker-compose.yml
```yaml
services:
  node-es-01:
    ...
    volumes:
      # ES Data
      - node-es-01-data:/usr/share/elasticsearch/data

volumes:
  node-es-01-data:
    driver: local
```
And my Dockerfile looks like this
```
FROM docker.elastic.co/elasticsearch/elasticsearch:6.4.0

# https://docs.search-guard.com/latest/search-guard-versions
ARG SG_ES_PACKAGE=com.floragunn:search-guard-6:6.4.0-23.0

RUN set -ex \
    && elasticsearch-plugin install --batch ${SG_ES_PACKAGE} \
    && cd /usr/share/elasticsearch/plugins/search-guard-6 \
    && chown -R elasticsearch /usr/share/elasticsearch/plugins/search-guard-6 \
    && chmod u+x /usr/share/elasticsearch/plugins/search-guard-6/tools/sgadmin.sh /usr/share/elasticsearch/plugins/search-guard-6/tools/hash.sh
```

Without SG, does your ES retain data between restarts ?
