### ISSUE TITLE
Kibana Internal Server Error When Accessing Unauthorized Index Pattern

### ISSUE THREAD

**Issue by Alsheh** [floragunncom/search-guard#636]
When a user attempts to access data in an index pattern to which the user doesn't have permission, the following Kibana error message gets logged:

<img width="1258" alt="52664718-9af62f80-2ebe-11e9-90ab-5b17935763d4" src="https://user-images.githubusercontent.com/16920445/54832728-f1068180-4c79-11e9-9697-d7e614cf1abb.png">

```
POST https://<kibana-host>/elasticsearch/_msearch?rest_total_hits_as_int=true&ignore_throttled=true 500 (Internal Server Error)
```

**Elasticsearch version**:  6.6.0
**Search Guard version**: 24.1
**Kibana SG plugin version**: 18

**Comment by floragunncom** [comment]
Can you please provide your sg_config.yml and kibana.yml as well as the logs from elasticsearch?

**Comment by Alsheh** [comment]
Elasticsearch doesn't produce any error logs besides the following:
```
[2019-02-20T18:58:53,117][WARN ][o.e.d.h.HttpInfo         ] [es-node-01] [http.publish_host] was printed as [ip:port] instead of [hostname/ip:port]. This format is deprecated and will change to [hostname/ip:port] in a future version. Use -Des.http.cname_in_publish_address=true to enforce non-deprecated formatting.
```

Steps to reproduce the error:
1. Enable enterprise modules with trial license in elasticsearch.yml:
```
searchguard.enterprise_modules_enabled: true
```


2. Set `do_not_fail_on_forbidden` to `true` in sg_config.yml:
```
...
searchguard:
  dynamic:
    # Set filtered_alias_mode to 'disallow' to forbid more than 2 filtered aliases per index
    # Set filtered_alias_mode to 'warn' to allow more than 2 filtered aliases per index but warns about it (default)
    # Set filtered_alias_mode to 'nowarn' to allow more than 2 filtered aliases per index silently
    #filtered_alias_mode: warn
    kibana:
      multitenancy_enabled: false
      server_username: 0.0.0.0
      index: '.kibana'
      do_not_fail_on_forbidden: true
...
```

3. Access an index pattern in Kibana to which the user doesn't have access
