### ISSUE TITLE
Strong performance issue when installing searchguard on one single node.

### ISSUE THREAD

**Issue by Soulou** [floragunncom/search-guard#649]
Hello,

We've identified a difference of performance of around 500/600% when the plugin search-guard is installed/initialized and without.

The problem has been detected when doing large queries:

Without the plugin:

```
└> time curl $url/products/_search?type=data' -d '{"query":{"bool":{"must":[],  "must_not":[], "should":[], "minimum_should_match":0}}, "from":0, "size":10000, "sort":[]}'  -o /dev/null
→ 1.067s total
```

With the plugin:

```
└> time curl "$url/products/_search?type=data' -d '{"query":{"bool":{"must":[],  "must_not":[], "should":[], "minimum_should_match":0}}, "from":0, "size":10000, "sort":[]}'  -o /dev/null
→ 6.313 total
```

We're using Search Guard 5 on ES 5.5.3.

Our configuration is the following (Nothing really special here)

```
searchguard:
  enable_snapshot_restore_privilege: true
  ssl:
    transport:
      pemcert_filepath: ./elasticsearch.crt.pem
      pemkey_filepath: ./elasticsearch.key.pem
      pemtrustedcas_filepath: ./ca.pem
      enforce_hostname_verification: false
      resolve_hostname: false
    http:
      enabled: true
      pemcert_filepath: ./elasticsearch.crt.pem
      pemkey_filepath: ./elasticsearch.key.pem
      pemtrustedcas_filepath: ./ca.pem

  authcz:
    admin_dn:
      - '<x509 subject>'
  nodes_dn:
    - '<x509 suhject>'
```

* We're running a single ES node
* We're not using ACL
* We're not using basic auth
* We've tested with OpenSSL dynamic/static binding, and we had some weird behavior (much more memory allocation, leading to a lot of garbage collecting and slower requests)
* ES instance is running in a container based on Ubuntu Xenial 16:04

What other parameters could we tweak, or notion we're missing here which could lead to such a performance difference. Because with this gap, it's just not usable.

Thank you very much. I'm available if you need any additional piece of information

**Comment by floragunncom** [comment]
Please attach your complete elasticsearch.yml and sg_config.yml and please provide also the response from the both curl commands (at least the metadata and the first few search results)

**Comment by Soulou** [comment]
elasticsearch.yml

```
indices.fielddata.cache.size: 60%
indices.breaker.fielddata.limit: 70%

searchguard:
  enable_snapshot_restore_privilege: true
  ssl:
    transport:
      pemcert_filepath: ./elasticsearch.crt.pem
      pemkey_filepath: ./elasticsearch.key.pem
      pemtrustedcas_filepath: ./ca.pem
      enforce_hostname_verification: false
      resolve_hostname: false
    http:
      enabled: true
      pemcert_filepath: ./elasticsearch.crt.pem
      pemkey_filepath: ./elasticsearch.key.pem
      pemtrustedcas_filepath: ./ca.pem

  authcz:
    admin_dn:
      - '<x509 subject>'
  nodes_dn:
    - '<x509 subject>'
```

Parameters set by launcher:

```
DAEMON_OPTS=("-p" "$PID_FILE" "-Edefault.path.logs=$LOG_DIR" "-Edefault.path.data=$DATA_DIR" "-Epath.repo=$BASE_DIR" "-Epath.conf=$CONF_DIR")
DAEMON_OPTS+=("-Ebootstrap.memory_lock=${ES_MEMORY_LOCK}")
DAEMON_OPTS+=("-Ecluster.name=$CLUSTER_NAME")
DAEMON_OPTS+=("-Enode.name=$ES_NODE_NAME")
DAEMON_OPTS+=("-Enetwork.bind_host=$ES_NETWORK")
DAEMON_OPTS+=("-Enetwork.publish_host=$PUBLIC_HOST")
DAEMON_OPTS+=("-Ediscovery.zen.ping.unicast.hosts=$ES_UNICAST_HOSTS")
DAEMON_OPTS+=("-Ediscovery.zen.minimum_master_nodes=$ES_MINIMUM_MASTER_NODES")
```

sg_config.yml

```
searchguard:
  dynamic:
    http:
      anonymous_auth_enabled: true
      xff:
        enabled: true
        remoteIpHeader: 'x-forwarded-for'
```

sg_roles.yml

```
sg_all_access:
  cluster:
    - UNLIMITED
  indices:
    '*':
      '*':
        - UNLIMITED
  tenants:
    adm_tenant: RW
    test_tenant_ro: RW
```

sg_action_groups.yml

```
UNLIMITED:
  - '*'
```

sg_internal_users.yml

```
# This is useless as we don't use Search Guard for the authentication part but this is
# mandatory to initialize Search Guard
readall:
  hash: $2a$12$ae4ycwzwvLtZxwZ82RmiEunBbIPiAmGZduBAjKN0TXdwQFtCwARz2
```

sg_roles_mapping.yml

```
sg_all_access:
  users:
    - '*'
```

Metadata WITH searchguard:

```json
{
   "took" : 152,
   "hits" : {
      "total" : 23944,
      "max_score" : 1,
      "hits" : [ ...]
     },
   "timed_out" : false,
   "_shards" : {
      "failed" : 0,
      "successful" : 5,
      "total" : 5
   }
}
```

Metadata WITHOUT searchguard

```
{
   "took" : 158,
   "hits" : {
      "total" : 23944,
      "max_score" : 1,
      "hits" : [ ...]
     },
   "timed_out" : false,
   "_shards" : {
      "failed" : 0,
      "successful" : 5,
      "total" : 5
   }
}
```
So the metadata of the requests are really identical, so I assume it's related to the action of the plugin/the encryption maybe (that's why I was speaking of the OpenSSL method, but it hasn't worked out as I would have expected).

Some additional note: the response body here is around 100MB

**Comment by floragunncom** [comment]
What is the effect on setting 
```
http:
      enabled: false
```
?

**Comment by floragunncom** [comment]
Maybe also related to https://github.com/floragunncom/search-guard/issues/310

**Comment by Soulou** [comment]
(FYI, I did some tests again with OpenSSL, it took 16 seconds with the dynamically linked, and the statically linked my client timed out)

I'm testing disabling HTTPS to see if it the cause, I'm coming back to you

**Comment by Soulou** [comment]
Confirmed, it's HTTPS leading to this problem, request time is back to normal.

What are the methods we could try to improve this?

**Comment by floragunncom** [comment]
Pls see https://github.com/floragunncom/search-guard/issues/310 and especially the last comment

**Comment by Soulou** [comment]
So basically we have to:

- Upgrade Java to Java 8 Update 141 (we are on Java 8 Update 191, so it should be ok)
- Upgrade Elasticsearch to branch 6.x?
- Freeze the ciphers to
  → `TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384` for Java SSL
  → `TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384` for OpenSSL

**Comment by floragunncom** [comment]
First thing I would try is to pin cipher for transport and http to "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384" and see how much it helps.
You can also try "TLS_DHE_RSA_WITH_AES_128_CBC_SHA256" or any other with CBC listed here https://github.com/floragunncom/search-guard-ssl/blob/master/src/main/java/com/floragunn/searchguard/ssl/util/SSLConfigConstants.java#L106

Also, make sure you have enough entropy on your system!

If this does not help I guess best is to upgrade to 6.6.1 because of ES 5.5 is already EOL and 5.6 will soon be.

**Comment by Soulou** [comment]
It's planned :-) Thanks for your advise, I'll update this issue with the results

**Comment by Soulou** [comment]
One note, our ES instance is interracting with Go which is not support DHE ciphers: https://github.com/golang/go/issues/20154 (and will never)

**Comment by Soulou** [comment]
OK I'm experiencing something weird:

```
    http:
      enabled: true
      pemcert_filepath: ./elasticsearch.crt.pem
      pemkey_filepath: ./elasticsearch.key.pem
      pemtrustedcas_filepath: ./ca.pem
      enabled_ciphers:
        - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
        - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA"
        - "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA"
        - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
        - "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256"
        - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384"
      enabled_protocols:
        - "TLSv1.2"
```

Then when I test the ciphers:

```
Testing TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
<nil> Get https://10.255.0.3:9200: x509: cannot validate certificate for 10.255.0.3 because it doesn't contain any IP SANs
Testing TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
<nil> Get https://10.255.0.3:9200: x509: cannot validate certificate for 10.255.0.3 because it doesn't contain any IP SANs
Testing TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
<nil> Get https://10.255.0.3:9200: x509: cannot validate certificate for 10.255.0.3 because it doesn't contain any IP SANs
Testing TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
<nil> Get https://10.255.0.3:9200: x509: cannot validate certificate for 10.255.0.3 because it doesn't contain any IP SANs
Testing TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
<nil> Get https://10.255.0.3:9200: remote error: tls: handshake failure
Testing TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
<nil> Get https://10.255.0.3:9200: remote error: tls: handshake failure
Testing TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
<nil> Get https://10.255.0.3:9200: remote error: tls: handshake failure
Testing TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
<nil> Get https://10.255.0.3:9200: remote error: tls: handshake failure
```

As if the ECDSA version weren't really supported, is it related to the certificate which has been created which has an RSA key? (I'm currently trying to change those)
