### ISSUE TITLE
Beats With ILM Enabled Failed To check For Alias: 403

### ISSUE THREAD

**Issue by Alsheh** [floragunncom/search-guard#694]
Auditbeat with ILM Enabled failed to check for Alias: 403

```
{
  "level": "error",
  "timestamp": "2019-05-07T01:20:53.284Z",
  "caller": "instance/ilm.go:80",
  "message": "Failed to check for alias: 403 Forbidden: : "
}
```
Auditbeat version: `6.7.1`
ES version: `6.7.1`
SG version: `25.0`

**Comment by jochenkressin** [comment]
Can you please add your beats configuration? Also, can you add the ES log file when the error is happening? That should reveal some more detailed information about why this is happening.

**Comment by floragunncom** [comment]
I guess ILM needs the "indices:admin/aliases*" permission for the indices which should be managed

**Comment by Alsheh** [comment]
ES logs:
```
...
[2019-05-09T22:17:01,777][WARN ][c.f.s.a.BackendRegistry  ] [es-client-03] Authentication finally failed for beats_system from <masked-remote-ip-address>:43394
[2019-05-09T22:12:35,046][INFO ][c.f.s.p.PrivilegesEvaluator] [es-client-03] No index-level perm match for User [name=beats_system, roles=[beats], requestedTenant=null] Resolved [aliases=[*], indices=[*], allIndices=[*], types=[*], originalRequested=[], remoteIndices=[]] [Action [indices:admin/aliases/get]] [RolesChecked [sg_xp_monitoring, sg_own_index, sg_beats_writer]]
...
```

`sg_beats_writer` permissions:
```
sg_beats_writer:
  cluster:
    - CLUSTER_MONITOR
    - CLUSTER_COMPOSITE_OPS
    - indices:admin/template/get
    - indices:admin/template/put
  indices:
    '*beat*':
      '*':
        - WRITE
        - CREATE_INDEX
        - MANAGE_ALIASES
```

Auditbeat relevant config:
```
...
output.elasticsearch:
  hosts: '${ES_HOSTS}'
  username: '${ES_USER}'
  password: '${ES_PWD}'
  index: 'auditbeat-${ENVIRONMENT_NAME}-%{+yyyy.MM.dd}'
  ilm.enabled: true
  ilm.rollover_alias: "auditbeat-${ENVIRONMENT_NAME}"
  ilm.pattern: "{now/d}-000001"
...
```

ES Template:
```
{
    "index_patterns" : "auditbeat-<ENVIRONMENT_NAME>",
    "order" : 2,
    "settings": {
	"index.lifecycle.name": "auditbeat"
    }
}
```

The `auditbeat` ILM policy was created on Kibana.

**Comment by Alsheh** [comment]
Related issue: https://github.com/elastic/beats/issues/10421

**Comment by floragunncom** [comment]
@Alsheh so can we close this one?

**Comment by Alsheh** [comment]
@floragunncom thanks for the follow up! In order to set up ILM policies , the following pre-defined [Elastic privileges are required](https://filebeatsecurityupdates.firebaseapp.com/feature-roles.html#privileges-to-setup-beats):
1. `manage_ilm`, `manage_index_templates`, and `monitor` on cluster. 
2. `manage` on  indices.

 I wonder what would be the SG privilege equivalent for `manage_ilm` to make ILM work?

**Comment by floragunncom** [comment]
Can you try

```
sg_logstash:  
  cluster:
    - CLUSTER_MONITOR
    - CLUSTER_COMPOSITE_OPS
    - "indices:admin/template/*"
    - "indices:admin/ilm/*"
    - cluster:admin/ingest/pipeline/put
    - cluster:admin/ingest/pipeline/get
  indices:
    'logstash-*':
      '*':
        - CRUD
        - CREATE_INDEX
        - MANAGE
    '*beat*':
      '*':
        - CRUD
        - CREATE_INDEX
        - MANAGE
```

**Comment by Alsheh** [comment]
@floragunncom the issue persists with the permissions you provided.

**Comment by floragunncom** [comment]
@pablolescotti can you have a look?

**Comment by thorntisen** [comment]
I was able to reproduce the issue. 

- It works with admin credentials, also with ilm.
- It does not work with permissions sg_beats_writer as specified within the topic.
- It does not work with sg_logstash default user. An error is:

    No permissions for [indices:admin/aliases/get]
  
   although user configuration contains 'indices:admin/aliases*' entry.

- The issue is related to ilm flag, because it works when I turn it off. 

According to official [documentation](https://www.elastic.co/guide/en/beats/auditbeat/6.7/ilm.html) of 6.7:

> This functionality is in beta and is subject to change. The design and code is less mature than official GA features and is being provided as-is with no warranties. Beta features are not subject to the support SLA of official GA features.

**Comment by thorntisen** [comment]
@Alsheh I am not familiar with the way auditbeat creates and manages indexes. If Your use case allows you to modify permissions of _sg_beats_writer_ from:
    
    indices:
        '*beat*':
          '*':
             - WRITE
             - CREATE_INDEX
             - MANAGE_ALIASES

to 

    indices:
        '*':
          '*':
            - WRITE
            - CREATE_INDEX
            - MANAGE_ALIASES

then it works.

**Comment by Alsheh** [comment]
@thorntisen thanks for your input! The admin access does work with `ilm` enabled, but, unfortunately, we need to limit the access of the `beats` user to the `beats` indices only.

**Comment by jochenkressin** [comment]
I tested this with  ES/SG V7, but it should also work with V6. Not that if you use any index other than the regular logstash and beats indices, you need to grant the permissions also to these indices. I have inserted a "<your index pattern>" placeholder in the configs:

Logstash ILM role V7 config:

```
sg_logstash_ilm:
  cluster_permissions:
    - CLUSTER_MONITOR
    - CLUSTER_COMPOSITE_OPS
    - 'indices:admin/template/*'
    - 'cluster:admin/ingest/pipeline/put'
    - 'cluster:admin/ingest/pipeline/'
    - 'cluster:admin/ilm/*'
  index_permissions:
    - index_patterns:
      - 'logstash-*'
      - '*beat*'
      - '<your index pattern>'
      allowed_actions:
        - CRUD
        - MANAGE
        - "indices:admin/ilm/*"
```

V6 style config:

```
sg_logstash_ilm:  
  cluster:
    - CLUSTER_MONITOR
    - CLUSTER_COMPOSITE_OPS
    - "indices:admin/template/*"
    - "cluster:admin/ingest/pipeline/put"
    - "cluster:admin/ingest/pipeline/"
    - "cluster:admin/ilm/*"
  indices:
    'logstash-*':
      '*':
        - CRUD
        - MANAGE
        - "indices:admin/ilm/*"
    '*beat*':
      '*':
        - CRUD
        - MANAGE
        - "indices:admin/ilm/*"
    '<your index pattern>':
      '*':
        - CRUD
        - MANAGE
        - "indices:admin/ilm/*" 
```

So for example, if you use an index alias in your ILM logstash config like:

`ilm_rollover_alias => "iis-iislog"`

You need to add this index pattern to the role definition as well.
