### ISSUE TITLE
Support user attributes in Proxy Authentication

### ISSUE THREAD

**Issue by mgorniew** [floragunncom/search-guard#721]
It is currently not possible to set user attributes when user is authenticated by proxy. It would be useful to allow proxy to set those parameters. This can be used to variable substitution, e.g. proxy would be able to decided which indices can user access. 

For example:

```
proxy_auth_domain:
  enabled: true
  order: 1
  http_authenticator:
    type: proxy
    challenge: false
    config:
      user_header: "x-proxy-user"
      roles_header: "x-proxy-roles"
      attributes_headers:
        attributeOne: "x-proxy-attr1"
        otherAttribute: "x-proxy-attr2"
  authentication_backend:
    type: noop
```

Would be eqiuvalent of user in internal database:

```
<value_of_x-proxy-user>:
  backend_roles:
  - <values_from_x-proxy-roles>
  attributes:
    attributeOne: <value_of_x-proxy-attr1>
    otherAttribute: <value_of_x-proxy-attr2>
```
